---
title: 'PS: Explore 1 Var - Udacity'
author: "KMS"
date: "May 10, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Set up ggplot library and load included diamonds library also get some high level good info
library(ggplot2)
data(diamonds)
summary(diamonds)
?diamonds
diamonds$color  #Levels: D < E < F < G < H < I < J
str(diamonds)
```

```{r diamond price hist}
names(diamonds)

qplot(x = price, data = diamonds)
ggsave('fig1_priceHist.png')

summary(diamonds$price)

```
### Diamond Price Summary
Notes: Median price is $2401, though heavy right tail skew drives the mean up to $3933
> summary(diamonds$price)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    326     950    2401    3933    5324   18820

```{r diamond value counts per cost}
less_500 <- subset(diamonds, price < 500) # = 1729
less_250 <- subset(diamonds, price < 250) # = 0
more_15000 <- subset(diamonds, price >= 15000) # = 1656

```


```{r diamond price hist  -  explore largest peak}
ggplot(aes(x = price), data = diamonds) + 
  geom_histogram(color = 'black', fill = '#F79420', binwidth = 10) + 
  scale_x_continuous(breaks = seq(0, 2000, 100), limits = c(0, 2000)) + 
  xlab('Price') + 
  ylab('Number of diamonds')
ggsave('fig2_priceHist_largestPeak.png')

```


```{r diamond price hist  -  by Cut}
qplot(x = price, data = diamonds) +
  facet_wrap(~cut)
ggsave('fig3_priceHistByCut.png')

by(diamonds$price, diamonds$cut, summary)
by(diamonds$price, diamonds$cut, max)
```
 
```{r diamond price hist  -  by Cut w/ free Y axis scales}
qplot(x = price, data = diamonds) +
  facet_wrap(~cut, scales="free")
ggsave('fig4_priceHistByCutDiffScalesY.png')

```

```{r diamond price hist  -  by Cut - log10 transform}
qplot(x = log10(price/carat), data = subset(diamonds, !is.na(cut)), binwidth=0.010) +
  facet_wrap(~cut, scales = "free_y")
ggsave('fig5_priceHistByCut_Log10tran.png')

```

```{r diamond price boxplot - cut and color}

qplot(x = cut, y = price, 
      data = subset(diamonds, !is.na(cut)),
      geom = 'boxplot', color = color) +
  coord_cartesian(ylim = c(250, 10000))
ggsave('fig6_price_boxplot_cut&color.png')

```


```{r diamond price IQR summary}
# The interquartile range of an observation variable is the difference of its upper and 
# lower quartiles. It is a measure of how far apart the middle portion of data spreads in value.
by(diamonds$price,diamonds$color, IQR)

by(diamonds$price,diamonds$color, summary)

```




